cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'imagemagick'
brew 'jp2a'
brew 'coreutils'
brew 'grc'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'legit'

cask '1password'
cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'transmission'
cask 'vlc'
cask 'franz'
cask 'spotify'
cask 'todoist'
cask 'dropbox'
cask 'alfred'
cask 'colorsnapper'
cask 'xscope'
cask 'istat-menus'
cask 'moom'
cask 'bartender'
cask 'caffine'
